databases:
  - name: rails_micropost_app
    databaseName: rails_micropost_app_production
    user: rails_micropost_app

services:
  - type: web
    name: rails-micropost-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
